//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
using System.Collections.Generic;

namespace Yahoo.Answer {
    using System.Xml.Serialization;
using System;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:yahoo:answers")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:yahoo:answers", IsNullable=false)]
    public partial class ResultSet {
        
        private QuestionType[] questionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Question")]
        public QuestionType[] Questions {
            get {
                return this.questionField;
            }
            set {
                this.questionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:yahoo:answers")]
	public partial class QuestionType
	{
        
        private string subjectField;
        
        private string contentField;
        
        private string dateField;
        
        private string timestampField;
        
        private string linkField;
        
        private CategoryType categoryField;
        
        private string userIdField;
        
        private string userNickField;
        
        private string userPhotoURLField;
        
        private string numAnswersField;
        
        private string numCommentsField;
        
        private string chosenAnswerField;
        
        private string chosenAnswererIdField;
        
        private string chosenAnswererNickField;
        
        private string chosenAnswerTimestampField;
        
        private string chosenAnswerAwardTimestampField;
        
        private string idField;
        
        private string typeField;
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public CategoryType Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserNick {
            get {
                return this.userNickField;
            }
            set {
                this.userNickField = value;
            }
        }
        
        /// <remarks/>
        public string UserPhotoURL {
            get {
                return this.userPhotoURLField;
            }
            set {
                this.userPhotoURLField = value;
            }
        }
        
        /// <remarks/>
        public string NumAnswers {
            get {
                return this.numAnswersField;
            }
            set {
                this.numAnswersField = value;
            }
        }
        
        /// <remarks/>
        public string NumComments {
            get {
                return this.numCommentsField;
            }
            set {
                this.numCommentsField = value;
            }
        }
        
        /// <remarks/>
        public string ChosenAnswer {
            get {
                return this.chosenAnswerField;
            }
            set {
                this.chosenAnswerField = value;
            }
        }
        
        /// <remarks/>
        public string ChosenAnswererId {
            get {
                return this.chosenAnswererIdField;
            }
            set {
                this.chosenAnswererIdField = value;
            }
        }
        
        /// <remarks/>
        public string ChosenAnswererNick {
            get {
                return this.chosenAnswererNickField;
            }
            set {
                this.chosenAnswererNickField = value;
            }
        }
        
        /// <remarks/>
        public string ChosenAnswerTimestamp {
            get {
                return this.chosenAnswerTimestampField;
            }
            set {
                this.chosenAnswerTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string ChosenAnswerAwardTimestamp {
            get {
                return this.chosenAnswerAwardTimestampField;
            }
            set {
                this.chosenAnswerAwardTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

	}
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:yahoo:answers")]
    public partial class CategoryType {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
